application: ap-open-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /announce
  script: announce.application
  
- url: /scrape
  script: scrape.application
  
- url: /
  script: active.application